<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ICEN062" failures="1" tests="2" name="Regression Test Suite" time="1.092" errors="0" timestamp="21 Jun 2018 10:07:35 GMT">
  <testcase classname="com.demo.packOne.demoOne" name="firstTestCase" time="1.031">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.demo.packOne.demoOne.firstTestCase() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.demo.packOne.demoOne.firstTestCase() didn't finish within the time-out 1000
at java.base@9.0.4/java.util.concurrent.FutureTask.setException(Unknown Source)
at java.base@9.0.4/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base@9.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base@9.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base@9.0.4/java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- firstTestCase -->
  <testcase classname="com.demo.packOne.demoOne" name="secondTestCase" time="0.005"/>
</testsuite> <!-- Regression Test Suite -->
