<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Regression Test Suite"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="1.036">
  <properties />
            <testcase name="firstTestCase" time="1.031" classname="com.demo.packOne.demoOne">
                <failure type="org.testng.internal.thread.ThreadTimeoutException"
                  message="Method com.demo.packOne.demoOne.firstTestCase() didn&apos;t finish within the time-out 1000"
              >
<![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.demo.packOne.demoOne.firstTestCase() didn't finish within the time-out 1000
  java.base@9.0.4/java.util.concurrent.FutureTask.setException(Unknown Source)
  java.base@9.0.4/java.util.concurrent.FutureTask.run(Unknown Source)
  java.base@9.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.base@9.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.base@9.0.4/java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="secondTestCase" time="0.005" classname="com.demo.packOne.demoOne" />
      
</testsuite>
